.travis.yml, manifests/add_udp_listen.pp, manifests/init.pp, spec/acceptance/add_tcp_stateful_listen_spec.rb, spec/classes/base_rules_spec.rb, spec/classes/coverage_spec.rb, spec/classes/init_spec.rb, spec/defines/add_tcp_stateful_listen_spec.rb, spec/defines/add_udp_listen_spec.rb
The acceptance tests for iptables::add_tcp_stateful_listen didn't
include IPv6.  This patch provides those tests (which pass).
SIMP-267 #close
=> (SIMP-267) Test IPv6 client_nets with iptables

build/pupmod-iptables.spec, manifests/init.pp, manifests/prevent_localhost_spoofing.pp, spec/classes/init_spec.rb, spec/classes/prevent_localhost_spoofing.rb, spec/spec_helper.rb
This patch ensures that IPv6 spoofed addresses will be rejected by
default.
Catalyst: https://access.redhat.com/articles/1305723
SIMP-45 #comment Full closure on the NTP issue
=> (SIMP-45) Prevent IPv6 ::1 spoofed addresses

spec/defines/add_tcp_stateful_listen_spec.rb
This patch adds spec tests to detect a reported bug where
iptables::add_tcp_stateful listen cannot add more than 10 ports.
SIMP-263 #close #comment Added spec tests.
=> (SIMP-263) Test that 1 rule can add >10 TCP ports

.fixtures.yml, .fixtures.yml.local, .puppet-lint.rc, .rspec, .travis.yml, Gemfile, Rakefile, build/pupmod-iptables.spec, lib/puppet/provider/iptables_rule/manage.rb, manifests/init.pp, metadata.json
Before this commit, common SIMP-related custom functions were been kept
in either `simp-common` or `simp-functions`, and the `concat` function
was provided by the `simp-concat` module.  These functions are now
provides by the `simp-simplib` and `simp-simpcat` modules, respectively.
This update replaces all requirements in the RPM spec file,
metadata.json, or .fixtures.yml to reflect the migration to the new
modules.
SIMP-601 #comment Migrated `pupmod-simp-iptables`.
SIMP-604 #comment Updated `pupmod-simp-iptables`.
=> (SIMP-604) Migrate to simplib and simpcat

.gitignore, .puppet-lint.rc, .travis.yml, CONTRIBUTING.md, Gemfile, build/pupmod-iptables.spec, manifests/add_all_listen.pp, manifests/add_icmp_listen.pp, manifests/add_tcp_stateful_listen.pp, manifests/init.pp, manifests/scanblock.pp, spec/acceptance/nodesets/centos-66-x64.yml, spec/acceptance/nodesets/centos-70-x64.yml, spec/acceptance/nodesets/default.yml, spec/spec_helper_acceptance.rb
This commit synchronizes all common static module assets with current SIMP
module standards.
Also:
- created metadata.json, .puppet-lint.rc, .travis.yml, .gitignore
- moved validations to the top of each class
- bumped RPM to 4.1.0-15
SIMP-667 #comment updated `pupmod-simp-iptables`
SIMP-734 #close #comment normalized common module assets
=> (SIMP-667) Normalize common module assets

build/pupmod-iptables.spec, manifests/init.pp
Changed default provider for iptables services to redhat because Puppet could
not enable them
SIMP-1001 #comment Fixes the pupmod-simp-iptables part of this story
SIMP-1002 #close
=> (SIMP-1002) Change default provider for iptables services

CHANGELOG, lib/puppet/provider/xt_recent/set.rb, lib/puppet/type/xt_recent.rb, manifests/scanblock.pp, metadata.json, spec/acceptance/add_tcp_stateful_listen_spec.rb, spec/acceptance/class_spec.rb, spec/acceptance/nodesets/default.yml, spec/defines/add_udp_listen_spec.rb
- Eliminated use of deprecated Puppet.newtype
- Fixed bug in the set provider for the xt_recent type that required manual
modifications to the permissions for the /sys/module/xt_recent/parameters/*
files, in order for the scanblock capability to be enabled.
- Fixed bugs in the xt_recent type and its set provider that caused
Puppet to believe /sys/module/xt_recent/parameters/ip_list_perms
file content had changed when it had not.
- Expanded acceptance tests
SIMP-1885 #close
=> (SIMP-1677) Remove deprecated Puppet.newtype

CHANGELOG, manifests/listen/tcp_stateful.pp, manifests/listen/udp.pp, metadata.json, spec/classes/init_spec.rb, spec/defines/listen/udp_spec.rb
- Updated iptables::listen::tcp_stateful and iptables::listen::udp
examples to pass valid Iptables::DestPort types to dports
SIMP-3498 #close
=> (SIMP-3498) Updated listen examples

CHANGELOG, build/rpm_metadata/requires, manifests/rules/scanblock.pp
scanblock rules would not properly ban hosts from
open ports due to rule ordering in IPTables. Default
order is now 7 instead of 28, right before the SSH
rule in IPTables.
SIMP-3311 #close
=> (SIMP-3311) Fixed IPTables scanblock rule ordering

.gitlab-ci.yml, .puppet-lint.rc, .travis.yml, CHANGELOG, Gemfile, lib/puppetx/simp/iptables.rb, manifests/init.pp, manifests/ports.pp, metadata.json, spec/classes/init_spec.rb, spec/defines/listen/ports_spec.rb, spec/defines/ports_spec.rb
This commit moves the logic that parses the `iptables::ports` hash into a define, to make it possible to use the same hash format in other modules without copying code. 
There was also a bug where compilation would fail if `proto` was specified in the defaults section of the hash.
=> iptables: Move ports logic to define

CHANGELOG, lib/puppet/provider/iptables_optimize/optimize.rb, lib/puppetx/simp/iptables.rb, metadata.json
- Fix issue where a `jump` target went to an empty ruleset and the chain
was dropped
- Retain all native IPTables jump points by default
- Retain Docker and Kubernetes rules by default
- Add `==` method for IPTables Rulesets
SIMP-4416 #comment IPTables fix due to bug exposed by kubernetes
=> (SIMP-4416) Fix issue with dropped chain

CHANGELOG, lib/puppet/functions/iptables/slice_ports.rb, spec/defines/listen/tcp_stateful_spec.rb, spec/defines/listen/udp_spec.rb, spec/functions/iptables/slice_ports_spec.rb, templates/allow_tcp_udp_services.erb
- Fixed bug in which port ranges specified by
iptables::listen::tcp_stateful::dports or
iptables::listen::udp::dports could be erroneously split
over multiple iptables rules
- Replaced deprecated simplib Puppet 3 function slice_array with
iptables::slice_ports
SIMP-6252 #comment pupmod-simp-iptables
SIMP-6322 #close
=> (SIMP-6252) Replace Puppet 3 slice_array

CHANGELOG, manifests/rules/base.pp, metadata.json
Added rule to drop 127.0.0.0/8 addresses as defined in
RFC 1122 - Section: 3.2.1.3(g). This will exclude 127.0.0.1 as it is
allowed in an earlier rule.
=> (SIMP-6242) Add rule to drop 127.0.0.0/8

CHANGELOG, manifests/ports.pp, metadata.json, spec/classes/init_spec.rb, spec/defines/ports_spec.rb, spec/fixtures/hieradata/iptables__ports_no_default.yaml
- Allow 'proto' in iptables::ports to be an array
- Bump version to 6.2.1
SIMP-4429 #close
=> (SIMP-4429) Allow 'proto' in iptables::ports to be an array

.fixtures.yml, Gemfile, REFERENCE.md, manifests/firewalld/rule.pp, manifests/firewalld/shim.pp, metadata.json, spec/acceptance/nodesets/oel.yml, spec/acceptance/suites/firewalld/00_default_spec.rb
* Bump upstream firewalld to 4.2.2 for backend selection support
* Set the default backend to 'iptables' to work around nftables bugs
* Ensure that firewalld service names do not contain a '.' character
* Fix missing entries in REFERENCE.md
SIMP-7538 #close
=> (SIMP-7538) Fix firewall service name strings

.gitlab-ci.yml, .travis.yml, Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7882 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-iptables
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-iptables
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
=> (SIMP-7848) Add PE2019.8 to pupmod-simp-iptables GL pipeline

CHANGELOG, lib/puppetx/simp/iptables/rule.rb, metadata.json
- Ensure that all addresses are normalized when rules are processed
- Remove nested looped rule normalization of addresses since it is no longer
required
- Fix normalize_addresses() so that it simply grabs the netmask if present and
slaps on the appropriate one if not
SIMP-8328 #comment Fix issue with iptables address normalization
=> (SIMP-8328) Fix iptables rule address normalization

CHANGELOG, README.md, REFERENCE.md, manifests/init.pp, metadata.json, spec/classes/init_spec.rb
Fixed:
* Ensure that firewalld is only enabled on systems that have it
installed.
SIMP-8613 #close
=> (SIMP-8613) appropriately configure firewalld

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_manual.yml, .github/workflows/pr_tests.yml, .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9306] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-iptables
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-iptables
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
=> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-iptables

CHANGELOG, data/os/CentOS-7.yaml, data/os/CentOS.yaml, data/os/OracleLinux-7.yaml, data/os/OracleLinux.yaml, data/os/RedHat-7.yaml, data/os/RedHat.yaml, data/os/windows.yaml, hiera.yaml, manifests/init.pp, manifests/install.pp, manifests/service.pp, spec/acceptance/nodesets/default.yml, spec/classes/init_spec.rb
- Fixed
- Moved the service-relevant files out of `install` and into `service`
- Ensure that EL8+ installs `iptables-service` instead of trying to install
the EL7 packages
- Call `iptables::install` in all enabled modes since `firewalld` may require
the underlying packages
=> (SIMP-9432) Fix EL8 packages

.github/workflows/pr_tests.yml, .gitignore, .gitlab-ci.yml, .puppet-lint.rc, Gemfile, REFERENCE.md, spec/spec_helper.rb
This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
=> Finalize RockyLinux 8 support
